### ISSUE TITLE
Conflict with EMI loot

### ISSUE THREAD

**Issue by SettingDust** [wisp-forest/gadget#34]
https://github.com/fzzyhmstrs/EMI_loot
https://github.com/fzzyhmstrs/EMI_loot/issues/40

```
[13:35:16] [Render thread/ERROR] (emi_loot) Failed to parse LootCondition of type net.minecraft.class_5339@6d5a2575 for stack translation{key='block.minecraft.air', args=[]} in table minecraft:entities/zombie_villager
[13:35:16] [Render thread/INFO] (Minecraft) [STDERR]: java.lang.IllegalStateException: Tried to mutate NBT tag while locked by NbtLocks#EMPTY
[13:35:16] [Render thread/INFO] (Minecraft) [STDERR]: 	at io.wispforest.gadget.nbt.LockableNbtInternal.gadget$checkWrite(LockableNbtInternal.java:18)
[13:35:16] [Render thread/INFO] (Minecraft) [STDERR]: 	at net.minecraft.class_1799.handler$gia000$gadget$checkMutability(class_1799.java:11130)
[13:35:16] [Render thread/INFO] (Minecraft) [STDERR]: 	at net.minecraft.class_1799.method_7980(class_1799.java)
[13:35:16] [Render thread/INFO] (Minecraft) [STDERR]: 	at net.minecraft.class_1799.method_7948(class_1799.java:526)
[13:35:16] [Render thread/INFO] (Minecraft) [STDERR]: 	at net.minecraft.class_1799.method_7974(class_1799.java:326)
[13:35:16] [Render thread/INFO] (Minecraft) [STDERR]: 	at fzzyhmstrs.emi_loot.parser.function.SetAnyDamageFunctionParser.parseFunction(SetAnyDamageFunctionParser.java:16)
[13:35:16] [Render thread/INFO] (Minecraft) [STDERR]: 	at fzzyhmstrs.emi_loot.parser.registry.LootParserRegistry.parseFunction(LootParserRegistry.java:50)
[13:35:16] [Render thread/INFO] (Minecraft) [STDERR]: 	at fzzyhmstrs.emi_loot.parser.LootTableParser.parseLootFunction(LootTableParser.java:524)
[13:35:16] [Render thread/INFO] (Minecraft) [STDERR]: 	at fzzyhmstrs.emi_loot.parser.LootTableParser.parseLootFunction(LootTableParser.java:504)
[13:35:16] [Render thread/INFO] (Minecraft) [STDERR]: 	at fzzyhmstrs.emi_loot.parser.LootTableParser.parseMobLootTableInternal(LootTableParser.java:289)
[13:35:16] [Render thread/INFO] (Minecraft) [STDERR]: 	at fzzyhmstrs.emi_loot.parser.LootTableParser.parseMobDirectLootTable(LootTableParser.java:273)
[13:35:16] [Render thread/INFO] (Minecraft) [STDERR]: 	at fzzyhmstrs.emi_loot.parser.LootTableParser.parseMobLootTable(LootTableParser.java:265)
[13:35:16] [Render thread/INFO] (Minecraft) [STDERR]: 	at fzzyhmstrs.emi_loot.parser.LootTableParser.parseEntityType(LootTableParser.java:195)
[13:35:16] [Render thread/INFO] (Minecraft) [STDERR]: 	at fzzyhmstrs.emi_loot.parser.LootTableParser.lambda$parseLootTables$7(LootTableParser.java:112)
[13:35:16] [Render thread/INFO] (Minecraft) [STDERR]: 	at java.base/java.lang.Iterable.forEach(Iterable.java:75)
[13:35:16] [Render thread/INFO] (Minecraft) [STDERR]: 	at fzzyhmstrs.emi_loot.parser.LootTableParser.parseLootTables(LootTableParser.java:106)
[13:35:16] [Render thread/INFO] (Minecraft) [STDERR]: 	at net.minecraft.class_4014.md2c4d76$emi_loot$lambda$emi_loot_readTablesAfterFabricForRealSimple$0$0(class_4014.java:523)
[13:35:16] [Render thread/INFO] (Minecraft) [STDERR]: 	at java.base/java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:787)
[13:35:16] [Render thread/INFO] (Minecraft) [STDERR]: 	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
[13:35:16] [Render thread/INFO] (Minecraft) [STDERR]: 	at java.base/java.util.concurrent.CompletableFuture.postFire(CompletableFuture.java:614)
[13:35:16] [Render thread/INFO] (Minecraft) [STDERR]: 	at java.base/java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:726)
[13:35:16] [Render thread/INFO] (Minecraft) [STDERR]: 	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)
[13:35:16] [Render thread/INFO] (Minecraft) [STDERR]: 	at net.minecraft.class_4014.method_18365(class_4014.java:69)
[13:35:16] [Render thread/INFO] (Minecraft) [STDERR]: 	at net.minecraft.class_1255.method_18859(class_1255.java:156)
[13:35:16] [Render thread/INFO] (Minecraft) [STDERR]: 	at net.minecraft.class_4093.method_18859(class_4093.java:23)
[13:35:16] [Render thread/INFO] (Minecraft) [STDERR]: 	at net.minecraft.class_1255.method_16075(class_1255.java:130)
[13:35:16] [Render thread/INFO] (Minecraft) [STDERR]: 	at net.minecraft.class_1255.method_18857(class_1255.java:139)
[13:35:16] [Render thread/INFO] (Minecraft) [STDERR]: 	at net.minecraft.class_310.method_18857(class_310.java:40031)
[13:35:16] [Render thread/INFO] (Minecraft) [STDERR]: 	at net.minecraft.class_7196.method_45694(class_7196.java:188)
[13:35:16] [Render thread/INFO] (Minecraft) [STDERR]: 	at net.minecraft.class_7196.method_41891(class_7196.java:123)
[13:35:16] [Render thread/INFO] (Minecraft) [STDERR]: 	at net.minecraft.class_7196.method_41899(class_7196.java:202)
[13:35:16] [Render thread/INFO] (Minecraft) [STDERR]: 	at net.minecraft.class_7196.method_41894(class_7196.java:64)
[13:35:16] [Render thread/INFO] (Minecraft) [STDERR]: 	at net.minecraft.class_528$class_4272.method_20174(class_528.java:590)
[13:35:16] [Render thread/INFO] (Minecraft) [STDERR]: 	at net.minecraft.class_528$class_4272.method_20164(class_528.java:480)
[13:35:16] [Render thread/INFO] (Minecraft) [STDERR]: 	at net.minecraft.class_528$class_4272.method_25402(class_528.java:407)
[13:35:16] [Render thread/INFO] (Minecraft) [STDERR]: 	at net.minecraft.class_350.method_25402(class_350.java:327)
[13:35:16] [Render thread/INFO] (Minecraft) [STDERR]: 	at net.minecraft.class_4069.method_25402(class_4069.java:38)
[13:35:16] [Render thread/INFO] (Minecraft) [STDERR]: 	at net.minecraft.class_312.method_1611(class_312.java:98)
[13:35:16] [Render thread/INFO] (Minecraft) [STDERR]: 	at net.minecraft.class_437.method_25412(class_437.java:409)
[13:35:16] [Render thread/INFO] (Minecraft) [STDERR]: 	at net.minecraft.class_312.method_1601(class_312.java:98)
[13:35:16] [Render thread/INFO] (Minecraft) [STDERR]: 	at net.minecraft.class_312.method_22686(class_312.java:169)
[13:35:16] [Render thread/INFO] (Minecraft) [STDERR]: 	at net.minecraft.class_1255.execute(class_1255.java:102)
[13:35:16] [Render thread/INFO] (Minecraft) [STDERR]: 	at net.minecraft.class_312.method_22684(class_312.java:169)
[13:35:16] [Render thread/INFO] (Minecraft) [STDERR]: 	at org.lwjgl.glfw.GLFWMouseButtonCallback$Container.invoke(GLFWMouseButtonCallback.java:81)
[13:35:16] [Render thread/INFO] (Minecraft) [STDERR]: 	at com.moulberry.axiom.editor.CustomImGuiImplGlfw.mouseButtonCallback(CustomImGuiImplGlfw.java:190)
[13:35:16] [Render thread/INFO] (Minecraft) [STDERR]: 	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:43)
[13:35:16] [Render thread/INFO] (Minecraft) [STDERR]: 	at org.lwjgl.system.JNI.invokeV(Native Method)
[13:35:16] [Render thread/INFO] (Minecraft) [STDERR]: 	at org.lwjgl.glfw.GLFW.glfwWaitEventsTimeout(GLFW.java:3474)
[13:35:16] [Render thread/INFO] (Minecraft) [STDERR]: 	at com.mojang.blaze3d.systems.RenderSystem.limitDisplayFPS(RenderSystem.java:237)
[13:35:16] [Render thread/INFO] (Minecraft) [STDERR]: 	at net.minecraft.class_310.method_1523(class_310.java:1244)
[13:35:16] [Render thread/INFO] (Minecraft) [STDERR]: 	at net.minecraft.class_310.method_1514(class_310.java:802)
[13:35:16] [Render thread/INFO] (Minecraft) [STDERR]: 	at net.minecraft.client.main.Main.main(Main.java:250)
[13:35:16] [Render thread/INFO] (Minecraft) [STDERR]: 	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468)
[13:35:16] [Render thread/INFO] (Minecraft) [STDERR]: 	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
[13:35:16] [Render thread/INFO] (Minecraft) [STDERR]: 	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
[13:35:16] [Render thread/INFO] (Minecraft) [STDERR]: 	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:87)
[13:35:16] [Render thread/INFO] (Minecraft) [STDERR]: 	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:130)
[13:35:16] [Render thread/INFO] (Minecraft) [STDERR]: 	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70)
```

**Comment by BasiqueEvangelist** [comment]
Oh dear...
You should be able to disable NBT locking in gadget for now, but I should probably investigate this

**Comment by BasiqueEvangelist** [comment]
mitigated with ca360b2de0c9c59410c1a3c038f5d380c72c5023, i'll investigate later™
